/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

import opaTest from "sap/ui/test/opaQunit";
import type { Given, When, Then } from "./types/OpaJourneyTypes.gen";
import runner from "./pages/JourneyRunner";

function journey() {
    QUnit.module("SpacefarersListListReport journey");

    const defaultTableId = "";

    opaTest("Start application", function (Given: Given, _When: When, Then: Then) {
        Given.iStartMyApp();

        Then.onTheSpacefarersListGenerated.iSeeThisPage();
    });

    opaTest("Check filter bar", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheSpacefarersListGenerated.onFilterBar().iCheckFilterField({ property: "originPlanet" });
        Then.onTheSpacefarersListGenerated.onFilterBar().iCheckFilterField({ property: "destinationPlanet" });
        Then.onTheSpacefarersListGenerated.onFilterBar().iCheckFilterField({ property: "spacesuitColor" });
        Then.onTheSpacefarersListGenerated.onFilterBar().iCheckFilterField({ property: "department" });
        Then.onTheSpacefarersListGenerated.onFilterBar().iCheckFilterField({ property: "position" });
    });

    // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
    // opaTest("Perform a global search and check the result", function (Given: Given, When: When, Then: Then) {
    //     When.onTheSpacefarersListGenerated.onFilterBar().iChangeSearchField("Search Term");
    //     When.onTheSpacefarersListGenerated.onFilterBar().iExecuteSearch();
    //     Then.onTheSpacefarersListGenerated.onTable(defaultTableId).iCheckRows();
    // });

    opaTest("Check table columns and actions", function (_Given: Given, _When: When, Then: Then) {
        Then.onTheSpacefarersListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"name":{"header":"Name"},"originPlanet":{"header":"Origin Planet"},"destinationPlanet":{"header":"Destination Planet"},"stardustCollection":{"header":"Stardust Collection"},"wormholeNavigationSkill":{"header":"Wormhole Nav. Skill"},"spacesuitColor":{"header":"Spacesuit Color"},"position":{"header":"Position"}});
    });

    opaTest("Navigate to ObjectPage", function (_Given: Given, When: When, Then: Then) {
        // Note: this test will fail if the ListReport page doesn't show any data
        When.onTheSpacefarersListGenerated.onFilterBar().iExecuteSearch();
        Then.onTheSpacefarersListGenerated.onTable(defaultTableId).iCheckRows();
        When.onTheSpacefarersListGenerated.onTable(defaultTableId).iPressRow(0);
        Then.onTheSpacefarersObjectPageGenerated.iSeeThisPage();
    });

    opaTest("Teardown", function (Given: Given) {
        // Cleanup
        Given.iTearDownMyApp();
    });
}

runner.run([journey]);
